base_url = "https://brentgervais.ca"
title = "Brent Gervais"
description = "Linux & open source podcaster, community builder, and specialized generalist. Co-host of LINUX Unplugged and host of Brunch With Brent on Jupiter Broadcasting. Based in Canada."
build_search_index = false